// Generates marketing/cover.html, the 630×500 itch.io cover art, from the game's real tile colours.
// Usage: node scripts/cover.mjs, then screenshot cover.html at 630×500 (see marketing/screenshots-guide.md).
import { writeFileSync } from 'node:fs';
import { el } from '../src/game/elements.js';

const ROWS = [
  [2, 10, 26, 26, 26],
  [29, 5, 18, 7, 36],
  [14, 12, 15, 17, 20],
];
const LIT = new Set(['0-2', '0-3', '0-4']);
const SIZE = 72;

const tile = (z, lit) => {
  const e = el(z);
  const p = e.palette;
  const style = `--c:${p.base};--cl:${p.light};--cd:${p.dark};--cg:${p.glow}`;
  return `<div class="tile${lit ? ' lit' : ''}" style="${style}"><span class="tile-z">${z}</span><span class="tile-sym">${e.symbol}</span><span class="tile-w">${e.weight}</span></div>`;
};

const board = ROWS.map((row, i) => row.map((z, j) => tile(z, LIT.has(`${i}-${j}`))).join('')).join('\n      ');

const html = `<!DOCTYPE html>
<!-- Generated by scripts/cover.mjs. Edit that, not this. -->
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Fusion Tiles cover</title>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&family=Space+Grotesk:wght@500;700&display=block" rel="stylesheet" />
<style>
  * { box-sizing: border-box; margin: 0; }
  html, body { width: 630px; height: 500px; overflow: hidden; background: #050914; }
  body {
    position: relative;
    font-family: 'Space Grotesk', system-ui, sans-serif;
    color: #e2e8f0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-image:
      radial-gradient(520px 300px at 50% 0%, rgba(56, 189, 248, 0.2), transparent 65%),
      radial-gradient(420px 320px at 108% 108%, rgba(167, 139, 250, 0.16), transparent 60%),
      radial-gradient(360px 280px at -10% 70%, rgba(45, 212, 191, 0.08), transparent 60%),
      linear-gradient(180deg, #070c1a 0%, #0b1222 100%);
  }
  .stars {
    position: absolute; inset: 0; opacity: 0.6;
    background-image:
      radial-gradient(1px 1px at 20px 30px, rgba(255,255,255,.55), transparent 60%),
      radial-gradient(1px 1px at 140px 90px, rgba(255,255,255,.35), transparent 60%),
      radial-gradient(1.5px 1.5px at 260px 180px, rgba(186,230,253,.5), transparent 60%),
      radial-gradient(1px 1px at 330px 40px, rgba(255,255,255,.3), transparent 60%),
      radial-gradient(1px 1px at 80px 250px, rgba(221,214,254,.45), transparent 60%);
    background-size: 360px 300px;
  }
  header { position: relative; display: flex; align-items: center; gap: 14px; }
  .atom { width: 46px; height: 46px; color: #7dd3fc; filter: drop-shadow(0 0 10px rgba(56,189,248,.9)); }
  h1 {
    font-size: 54px; font-weight: 700; letter-spacing: 0.1em; color: #fff; line-height: 1;
    text-shadow: 0 0 18px rgba(56,189,248,.6), 0 0 44px rgba(56,189,248,.3);
  }
  .tagline {
    position: relative; margin-top: 12px;
    font: 400 11px 'JetBrains Mono', monospace; letter-spacing: 0.3em; color: rgba(125,211,252,.7);
  }
  .board {
    position: relative; margin-top: 26px; padding: 9px;
    display: grid; grid-template-columns: repeat(5, ${SIZE}px); gap: 8px;
    border-radius: 20px; border: 1px solid rgba(148,163,184,.14);
    background: radial-gradient(120% 90% at 50% 0%, rgba(56,189,248,.08), transparent 60%), rgba(6,11,26,.85);
    box-shadow: 0 30px 70px -30px #000, inset 0 0 50px rgba(56,189,248,.05), inset 0 1px 0 rgba(255,255,255,.05);
  }
  .tile {
    position: relative; width: ${SIZE}px; height: ${SIZE}px; border-radius: 20%; color: #fff; overflow: hidden;
    --u: ${(SIZE / 16.67).toFixed(2)}px;
    background:
      radial-gradient(120% 80% at 30% 0%, rgba(255,255,255,.32), transparent 55%),
      linear-gradient(160deg, var(--cl) 0%, var(--c) 48%, var(--cd) 100%);
    box-shadow: inset 0 1px 0 rgba(255,255,255,.45), inset 0 -3px 0 rgba(0,0,0,.22), 0 3px 8px -2px rgba(0,0,0,.65);
  }
  .tile::after { content: ''; position: absolute; inset: 0; border-radius: inherit; border: 1px solid rgba(255,255,255,.22); }
  .tile.lit {
    overflow: visible;
    box-shadow: inset 0 1px 0 rgba(255,255,255,.45), inset 0 -3px 0 rgba(0,0,0,.22), 0 0 26px 2px var(--cg), 0 0 0 2px rgba(255,255,255,.7);
  }
  .tile-z, .tile-w {
    position: absolute; font-family: 'JetBrains Mono', monospace; font-size: calc(var(--u) * 2.05);
    line-height: 1; opacity: .82; text-shadow: 0 1px 1px rgba(0,0,0,.35);
  }
  .tile-z { top: 9%; left: 11%; font-weight: 700; }
  .tile-w { bottom: 9%; left: 0; right: 0; text-align: center; opacity: .7; }
  .tile-sym {
    position: absolute; inset: 0; display: grid; place-items: center; padding-bottom: 4%;
    font-weight: 700; font-size: calc(var(--u) * 6.1); letter-spacing: -0.02em;
    text-shadow: 0 1px 0 rgba(0,0,0,.25), 0 2px 10px rgba(0,0,0,.25);
  }
  footer { position: relative; margin-top: 22px; font-size: 13px; color: #8b9ab5; letter-spacing: 0.02em; }
  footer b { color: #e2e8f0; font-weight: 500; }
</style>
</head>
<body>
  <div class="stars"></div>
  <header>
    <svg class="atom" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="12" cy="12" r="1" />
      <path d="M20.2 20.2c2.04-2.03.02-7.36-4.5-11.9-4.52-4.52-9.87-6.54-11.9-4.5-2.04 2.03-.02 7.36 4.5 11.9 4.52 4.52 9.87 6.54 11.9 4.5Z" />
      <path d="M15.7 15.7c4.52-4.54 6.54-9.87 4.5-11.9-2.03-2.04-7.36-.02-11.9 4.5-4.52 4.52-6.54 9.87-4.5 11.9 2.03 2.04 7.36.02 11.9-4.5Z" />
    </svg>
    <h1>FUSION TILES</h1>
  </header>
  <div class="tagline">MATCH · FUSE · CLIMB THE PERIODIC TABLE</div>
  <div class="board">
      ${board}
  </div>
  <footer><b>All 118 real elements</b> · How far up the table can you go?</footer>
</body>
</html>
`;

writeFileSync(new URL('../marketing/cover.html', import.meta.url), html);
console.log('wrote marketing/cover.html');
